<?php

/**
 * BaseDeals
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $image
 * @property string $description
 * @property integer $value
 * @property date $start
 * @property date $end
 * @property integer $restaurant_id
 * @property Restaurant $Restaurant
 * 
 * @method string     getImage()         Returns the current record's "image" value
 * @method string     getDescription()   Returns the current record's "description" value
 * @method integer    getValue()         Returns the current record's "value" value
 * @method date       getStart()         Returns the current record's "start" value
 * @method date       getEnd()           Returns the current record's "end" value
 * @method integer    getRestaurantId()  Returns the current record's "restaurant_id" value
 * @method Restaurant getRestaurant()    Returns the current record's "Restaurant" value
 * @method Deals      setImage()         Sets the current record's "image" value
 * @method Deals      setDescription()   Sets the current record's "description" value
 * @method Deals      setValue()         Sets the current record's "value" value
 * @method Deals      setStart()         Sets the current record's "start" value
 * @method Deals      setEnd()           Sets the current record's "end" value
 * @method Deals      setRestaurantId()  Sets the current record's "restaurant_id" value
 * @method Deals      setRestaurant()    Sets the current record's "Restaurant" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDeals extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('deals');
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('start', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('end', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('restaurant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Restaurant', array(
             'local' => 'restaurant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}