<?php

/**
 * BaseCart
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $client_id
 * @property integer $restaurant_id
 * @property string $product_id
 * @property boolean $status
 * @property float $total
 * @property Restaurant $Restaurant
 * @property Entity $Entity
 * 
 * @method integer    getClientId()      Returns the current record's "client_id" value
 * @method integer    getRestaurantId()  Returns the current record's "restaurant_id" value
 * @method string     getProductId()     Returns the current record's "product_id" value
 * @method boolean    getStatus()        Returns the current record's "status" value
 * @method float      getTotal()         Returns the current record's "total" value
 * @method Restaurant getRestaurant()    Returns the current record's "Restaurant" value
 * @method Entity     getEntity()        Returns the current record's "Entity" value
 * @method Cart       setClientId()      Sets the current record's "client_id" value
 * @method Cart       setRestaurantId()  Sets the current record's "restaurant_id" value
 * @method Cart       setProductId()     Sets the current record's "product_id" value
 * @method Cart       setStatus()        Sets the current record's "status" value
 * @method Cart       setTotal()         Sets the current record's "total" value
 * @method Cart       setRestaurant()    Sets the current record's "Restaurant" value
 * @method Cart       setEntity()        Sets the current record's "Entity" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCart extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cart');
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('restaurant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('total', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Restaurant', array(
             'local' => 'restaurant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Entity', array(
             'local' => 'client_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}