<?php

/**
 * BaseRestaurant
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $entity_id
 * @property string $image
 * @property string $name
 * @property string $address
 * @property string $city
 * @property string $postal_code
 * @property string $type
 * @property string $phone
 * @property string $description
 * @property time $open_time
 * @property time $close_time
 * @property boolean $status
 * @property Entity $Entity
 * @property Doctrine_Collection $Restaurants3
 * @property Doctrine_Collection $Restaurants4
 * @property Doctrine_Collection $Restaurants
 * @property Doctrine_Collection $Restaurants2
 * 
 * @method integer             getEntityId()     Returns the current record's "entity_id" value
 * @method string              getImage()        Returns the current record's "image" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getAddress()      Returns the current record's "address" value
 * @method string              getCity()         Returns the current record's "city" value
 * @method string              getPostalCode()   Returns the current record's "postal_code" value
 * @method string              getType()         Returns the current record's "type" value
 * @method string              getPhone()        Returns the current record's "phone" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method time                getOpenTime()     Returns the current record's "open_time" value
 * @method time                getCloseTime()    Returns the current record's "close_time" value
 * @method boolean             getStatus()       Returns the current record's "status" value
 * @method Entity              getEntity()       Returns the current record's "Entity" value
 * @method Doctrine_Collection getRestaurants3() Returns the current record's "Restaurants3" collection
 * @method Doctrine_Collection getRestaurants4() Returns the current record's "Restaurants4" collection
 * @method Doctrine_Collection getRestaurants()  Returns the current record's "Restaurants" collection
 * @method Doctrine_Collection getRestaurants2() Returns the current record's "Restaurants2" collection
 * @method Restaurant          setEntityId()     Sets the current record's "entity_id" value
 * @method Restaurant          setImage()        Sets the current record's "image" value
 * @method Restaurant          setName()         Sets the current record's "name" value
 * @method Restaurant          setAddress()      Sets the current record's "address" value
 * @method Restaurant          setCity()         Sets the current record's "city" value
 * @method Restaurant          setPostalCode()   Sets the current record's "postal_code" value
 * @method Restaurant          setType()         Sets the current record's "type" value
 * @method Restaurant          setPhone()        Sets the current record's "phone" value
 * @method Restaurant          setDescription()  Sets the current record's "description" value
 * @method Restaurant          setOpenTime()     Sets the current record's "open_time" value
 * @method Restaurant          setCloseTime()    Sets the current record's "close_time" value
 * @method Restaurant          setStatus()       Sets the current record's "status" value
 * @method Restaurant          setEntity()       Sets the current record's "Entity" value
 * @method Restaurant          setRestaurants3() Sets the current record's "Restaurants3" collection
 * @method Restaurant          setRestaurants4() Sets the current record's "Restaurants4" collection
 * @method Restaurant          setRestaurants()  Sets the current record's "Restaurants" collection
 * @method Restaurant          setRestaurants2() Sets the current record's "Restaurants2" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRestaurant extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('restaurant');
        $this->hasColumn('entity_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('city', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('postal_code', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('open_time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('close_time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('status', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Entity', array(
             'local' => 'entity_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Deals as Restaurants3', array(
             'local' => 'id',
             'foreign' => 'restaurant_id'));

        $this->hasMany('Comments as Restaurants4', array(
             'local' => 'id',
             'foreign' => 'restaurant_id'));

        $this->hasMany('Category as Restaurants', array(
             'local' => 'id',
             'foreign' => 'restaurant_id'));

        $this->hasMany('Cart as Restaurants2', array(
             'local' => 'id',
             'foreign' => 'restaurant_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
              1 => 'city',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}