<?php

/**
 * BaseDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $size
 * @property Doctrine_Collection $Details
 * 
 * @method string              getSize()    Returns the current record's "size" value
 * @method Doctrine_Collection getDetails() Returns the current record's "Details" collection
 * @method Detail              setSize()    Sets the current record's "size" value
 * @method Detail              setDetails() Sets the current record's "Details" collection
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detail');
        $this->hasColumn('size', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product as Details', array(
             'local' => 'id',
             'foreign' => 'detail_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}