<?php

/**
 * BaseComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $text
 * @property integer $member_id
 * @property integer $restaurant_id
 * @property integer $note
 * @property Entity $Entity
 * @property Restaurant $Restaurant
 * 
 * @method string     getText()          Returns the current record's "text" value
 * @method integer    getMemberId()      Returns the current record's "member_id" value
 * @method integer    getRestaurantId()  Returns the current record's "restaurant_id" value
 * @method integer    getNote()          Returns the current record's "note" value
 * @method Entity     getEntity()        Returns the current record's "Entity" value
 * @method Restaurant getRestaurant()    Returns the current record's "Restaurant" value
 * @method Comments   setText()          Sets the current record's "text" value
 * @method Comments   setMemberId()      Sets the current record's "member_id" value
 * @method Comments   setRestaurantId()  Sets the current record's "restaurant_id" value
 * @method Comments   setNote()          Sets the current record's "note" value
 * @method Comments   setEntity()        Sets the current record's "Entity" value
 * @method Comments   setRestaurant()    Sets the current record's "Restaurant" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comments');
        $this->hasColumn('text', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('restaurant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('note', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Entity', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Restaurant', array(
             'local' => 'restaurant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}