<?php

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $image
 * @property integer $restaurant_id
 * @property integer $category_id
 * @property integer $detail_id
 * @property string $name
 * @property string $description
 * @property float $price
 * @property Restaurant $Restaurant
 * @property Category $Category
 * @property Detail $Detail
 * 
 * @method string     getImage()         Returns the current record's "image" value
 * @method integer    getRestaurantId()  Returns the current record's "restaurant_id" value
 * @method integer    getCategoryId()    Returns the current record's "category_id" value
 * @method integer    getDetailId()      Returns the current record's "detail_id" value
 * @method string     getName()          Returns the current record's "name" value
 * @method string     getDescription()   Returns the current record's "description" value
 * @method float      getPrice()         Returns the current record's "price" value
 * @method Restaurant getRestaurant()    Returns the current record's "Restaurant" value
 * @method Category   getCategory()      Returns the current record's "Category" value
 * @method Detail     getDetail()        Returns the current record's "Detail" value
 * @method Product    setImage()         Sets the current record's "image" value
 * @method Product    setRestaurantId()  Sets the current record's "restaurant_id" value
 * @method Product    setCategoryId()    Sets the current record's "category_id" value
 * @method Product    setDetailId()      Sets the current record's "detail_id" value
 * @method Product    setName()          Sets the current record's "name" value
 * @method Product    setDescription()   Sets the current record's "description" value
 * @method Product    setPrice()         Sets the current record's "price" value
 * @method Product    setRestaurant()    Sets the current record's "Restaurant" value
 * @method Product    setCategory()      Sets the current record's "Category" value
 * @method Product    setDetail()        Sets the current record's "Detail" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('restaurant_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('detail_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('price', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Restaurant', array(
             'local' => 'restaurant_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Detail', array(
             'local' => 'detail_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}