<?php

/**
 * BaseCities
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nom
 * @property string $cp
 * @property float $latitude
 * @property float $longitude
 * @property string $eloignement
 * @property string $url
 * 
 * @method string getNom()         Returns the current record's "nom" value
 * @method string getCp()          Returns the current record's "cp" value
 * @method float  getLatitude()    Returns the current record's "latitude" value
 * @method float  getLongitude()   Returns the current record's "longitude" value
 * @method string getEloignement() Returns the current record's "eloignement" value
 * @method string getUrl()         Returns the current record's "url" value
 * @method Cities setNom()         Sets the current record's "nom" value
 * @method Cities setCp()          Sets the current record's "cp" value
 * @method Cities setLatitude()    Sets the current record's "latitude" value
 * @method Cities setLongitude()   Sets the current record's "longitude" value
 * @method Cities setEloignement() Sets the current record's "eloignement" value
 * @method Cities setUrl()         Sets the current record's "url" value
 * 
 * @package    test
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCities extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cities');
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cp', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('latitude', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('longitude', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('eloignement', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}