<?php

/**
 * DealsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Deals');
    }
    
    public function getRecentDeals()
    {
      return $this->createQuery('p')
        ->where('p.created_at > ?', date('Y-m-d H:i:s', time() - 86400 * 30))
        ->execute();
    }
    
    public function getBestDeals()
    {
      return $this->createQuery('p')
        ->andWhere('p.start != ?', '0000-00-00 00:00:00')
        ->andWhere('p.end != ?', '0000-00-00 00:00:00')
        ->orderBy('p.value DESC')
        ->limit(10)
        ->execute();
    }
    
    public function getPermanentDeals()
    {
      return $this->createQuery('p')
        ->where('p.start = ?', '0000-00-00 00:00:00')
        ->andWhere('p.end = ?', '0000-00-00 00:00:00')
        ->orderBy('p.value DESC')
        ->limit(10)
        ->execute();
    }
    
    public function getDealsById($restaurantId)
    {
      return $this->createQuery('p')
        ->where('p.restaurant_id = ?', $restaurantId)
        ->execute();
    }
    
    public function getLatestDeals($restaurantId)
    {
      return $this->createQuery('p')
        ->orderBy('p.created_at DESC')
        ->limit(5)
        ->execute();
    }
}