<?php

/**
 * DetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Detail');
    }
}