<?php

/**
 * ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product');
    }

    public function getAllByRestaurantId($restaurantId)
    {
      return $this->createQuery('p')
       ->where('restaurant_id = ?', $restaurantId);
    }

    public function findOne($id)
    {
      return $this->createQuery('p')
        ->where('product_id = ?', $id)
        ->execute();
    }
}
