<?php

/**
 * RestaurantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RestaurantTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object RestaurantTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Restaurant');
  }

  public function getAll() {
    return $this->createQuery('r')
                    ->execute();
  }

  public function getOneBySlug($options) {
    return $this->createQuery('r')
                    ->where('r.slug = ?', $options['slug'])
                    ->fetchOne();
  }

  public function getCities() {
    return $this->createQuery('r')
                    ->groupBy('r.city')
                    ->execute();
  }

  public function getLatestRestaurants() {
    return $this->createQuery('r')
                    ->orderBy('r.created_at DESC')
                    ->limit(5)
                    ->execute();
  }

  public function getAllByPostalCode($postal_code) {
    return $this->createQuery('r')
                    ->where('r.postal_code = ?', $postal_code)
                    ->execute();
  }

  public static function findCityByName($name, $limit=10) {
    return Doctrine_Core::getTable('Restaurant')
                    ->createQuery('r')
                    ->select("city, postal_code")
                    ->where("r.city LIKE '$name%'")
                    ->groupby("postal_code")
                    ->limit($limit)
                    ->execute(array(), Doctrine::HYDRATE_NONE);
  }

  public static function findCityByZipCode($zipcode, $limit=10) {
    return Doctrine_Core::getTable('Restaurant')
                    ->createQuery('r')
                    ->select("city")
                    ->where("r.postal_code LIKE '$zipcode%'")
                    ->limit($limit)
                    ->execute(array(), Doctrine::HYDRATE_NONE);
  }

}
