<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/07/15 23:14:42
$this->security = array (
  'signup' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
