<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/07/15 23:52:23
$this->security = array (
  'signup' => 
  array (
    'is_secure' => false,
  ),
  'contact' => 
  array (
    'is_secure' => false,
  ),
  'qui' => 
  array (
    'is_secure' => false,
  ),
  'concept' => 
  array (
    'is_secure' => false,
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
