<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/15 23:19:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=testsf',
  'username' => 'testsf',
  'password' => 'Eh1oegii',
  'name' => 'doctrine',
)),);
